### PR TITLE
add of DeliverySection Component

### PR DESCRIPTION
**Pull request by FloCheru**
Problem :
h2 title is wraping while I have 
- font-size: 33px;
- font-weight: 700;
 - font-family: Roboto, sans-serif;
 - width: 518px;
 - line-height: 41.02px;
 
 like on Figma file. I don't how to make it not wrap while having same parameters than written on Figma

### CODE REVIEW

**Comment by bruno-keiko** [comment]
> Problem : h2 title is wraping while I have
> 
> * font-size: 33px;
> * font-weight: 700;
> * font-family: Roboto, sans-serif;
> * width: 518px;
> * line-height: 41.02px;
> 
> like on Figma file. I don't how to make it not wrap while having same parameters than written on Figma

Could you try   white-space: nowrap; this one . If you create a story file, we will allow you to see your work.

**Comment by FloCheru** [comment]
Story file is ready

**Comment by FloCheru** [comment]
Fixes #64

**Review by bruno-keiko — CHANGES_REQUESTED** [review]
Great Job! Could you resolve the confliction? I think you should rebase it

**Comment by FloCheru** [comment]
Why does the _colors.scss file stay in conflict ?

**Review by bruno-keiko — APPROVED** [review]

**Comment by FloCheru** [comment]
Issue #64 is still opened

**Comment by bruno-keiko** [comment]
> Issue #64 is still opened

Oh, thank you! I forgot to close it. It would be great if next time you mention your closed issue in the PRs description. GitHub tells us that a Pull Request belongs to a closed issue.

**Pull request merged**
