### PR TITLE
feat(component): added BasketButton

### PR DESCRIPTION
**Pull request by Hudayberdiev2000**

### CODE REVIEW

**Review by bruno-keiko — CHANGES_REQUESTED** [review]
Please fix linting errors `npm run lint` or `npm run lint:fix`

**Comment by Hudayberdiev2000** [comment]
Fixed the linting errors!

**Comment by bruno-keiko** [comment]
> Fixed the linting errors!

We have border-radius variables. Could you use it?

**Comment by bruno-keiko** [comment]
Could you update the root branch and resolve conflicts?

**Comment by Hudayberdiev2000** [comment]
in last commit i updated root branch, and merged it to this branch.

**Comment by bruno-keiko** [comment]
> in last commit i updated root branch, and merged it to this branch.

Use rebase for clean commit history and resolve confilicts

**Comment by Hudayberdiev2000** [comment]
I've made the changes you told me.

**Pull request merged**
